# Generated by Django 5.2.4 on 2025-08-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trial_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_duration_days',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
