# Generated by Django 5.2.4 on 2025-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_trial_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du modèle')),
                ('template_file', models.CharField(max_length=255, verbose_name='Chemin du fichier template')),
                ('is_default', models.BooleanField(default=False, verbose_name='Utiliser par défaut')),
            ],
        ),
    ]
