# Generated by Django 5.2.4 on 2025-08-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoicetemplate', verbose_name='Modèle de facture'),
        ),
    ]
