# Generated by Django 5.2.4 on 2025-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='Aperçu du modèle'),
        ),
    ]
