# Generated by Django 5.2.4 on 2025-08-15 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoicetemplate_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('description', models.TextField(verbose_name='Description du programme')),
                ('questions', models.JSONField(verbose_name='Questions de la formation (format JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'En formation'), ('completed', 'Formation terminée'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('progression', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('last_question_index', models.IntegerField(default=0, verbose_name='Index de la dernière question')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Date de début du contrat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_partners', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
        ),
    ]
