# Generated by Django 5.2.4 on 2025-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_formation_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='failed_attempts',
            field=models.IntegerField(default=0, verbose_name='Tentatives échouées'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Score'),
        ),
    ]
