# Generated by Django 5.2.4 on 2025-08-15 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partenaire_failed_attempts_partenaire_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux de commission (%)'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin du contrat'),
        ),
    ]
