# Generated by Django 5.2.4 on 2025-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partenaire_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code de parrainage'),
        ),
    ]
