# Generated by Django 5.2.4 on 2025-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partenaire_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du support')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='marketing_materials/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Support marketing',
                'verbose_name_plural': 'Supports marketing',
            },
        ),
    ]
