# Generated by Django 5.2.4 on 2025-08-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_parrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_paid_subscription',
            field=models.BooleanField(default=False, verbose_name='Abonnement payant'),
        ),
    ]
