# Generated by Django 5.2.4 on 2025-08-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_has_paid_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_paid_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
