# Generated by Django 5.2.4 on 2025-08-16 04:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
