# Generated by Django 5.2.4 on 2025-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_partenaire_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
    ]
