# Generated by Django 5.2.4 on 2025-08-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_commission_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='parrain',
            new_name='referred_by',
        ),
    ]
