# Generated by Django 5.2.4 on 2025-08-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_parrain_customuser_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En formation'), ('completed', 'Formation terminée'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='in_progress', max_length=20, verbose_name='Statut'),
        ),
    ]
