# Generated by Django 5.2.4 on 2025-08-17 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_partenaire_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='partner',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='partenaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='core.partenaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('airtel_money', 'Airtel Money'), ('bank_transfer', 'Virement Bancaire')], default='orange_money', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
