# Generated by Django 5.2.4 on 2025-08-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_withdrawalrequest_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_details',
            field=models.CharField(default='', help_text='Numéro de téléphone ou informations bancaires pour le paiement.', max_length=255),
            preserve_default=False,
        ),
    ]
